[2020-04-22 06:01:53,459] INFO [GroupCoordinator 0]: Member kafka-python-2.0.1-d7b0f4e5-e785-4faa-8df2-11dcd21aa49d in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:01:53,460] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 26 (__consumer_offsets-12) (reason: removing member kafka-python-2.0.1-d7b0f4e5-e785-4faa-8df2-11dcd21aa49d on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:01:53,460] INFO [GroupCoordinator 0]: Group my-group with generation 27 is now empty (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:02:40,536] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group my-group in Empty state. Created a new member id kafka-python-2.0.1-d539ca4c-d004-46c8-bf6c-e3addebe92c9 for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:02:40,537] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 27 (__consumer_offsets-12) (reason: Adding new member kafka-python-2.0.1-d539ca4c-d004-46c8-bf6c-e3addebe92c9 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:02:40,537] INFO [GroupCoordinator 0]: Stabilized group my-group generation 28 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:02:40,539] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 28 (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:03:18,456] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group my-group in Stable state. Created a new member id kafka-python-2.0.1-0c51abc4-a5b5-4396-9ac2-6f7ba14799a7 for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:03:18,457] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 28 (__consumer_offsets-12) (reason: Adding new member kafka-python-2.0.1-0c51abc4-a5b5-4396-9ac2-6f7ba14799a7 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:03:20,588] INFO [GroupCoordinator 0]: Member kafka-python-2.0.1-d539ca4c-d004-46c8-bf6c-e3addebe92c9 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:03:20,590] INFO [GroupCoordinator 0]: Stabilized group my-group generation 29 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:03:20,592] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 29 (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:03:36,601] INFO [GroupCoordinator 0]: Member kafka-python-2.0.1-0c51abc4-a5b5-4396-9ac2-6f7ba14799a7 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:03:36,602] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 29 (__consumer_offsets-12) (reason: removing member kafka-python-2.0.1-0c51abc4-a5b5-4396-9ac2-6f7ba14799a7 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:03:36,602] INFO [GroupCoordinator 0]: Group my-group with generation 30 is now empty (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:04:44,527] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group my-group in Empty state. Created a new member id kafka-python-2.0.1-31fdee65-ab1f-449b-adb6-5a8a74c824f4 for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:04:44,528] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 30 (__consumer_offsets-12) (reason: Adding new member kafka-python-2.0.1-31fdee65-ab1f-449b-adb6-5a8a74c824f4 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:04:44,528] INFO [GroupCoordinator 0]: Stabilized group my-group generation 31 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:04:44,530] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 31 (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:05:31,012] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group my-group in Stable state. Created a new member id kafka-python-2.0.1-c2e0c9a9-34cf-4961-8282-81a07688eee9 for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:05:31,012] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 31 (__consumer_offsets-12) (reason: Adding new member kafka-python-2.0.1-c2e0c9a9-34cf-4961-8282-81a07688eee9 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:05:34,584] INFO [GroupCoordinator 0]: Member kafka-python-2.0.1-31fdee65-ab1f-449b-adb6-5a8a74c824f4 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:05:34,585] INFO [GroupCoordinator 0]: Stabilized group my-group generation 32 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:05:34,587] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 32 (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:06:12,617] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group my-group in Stable state. Created a new member id kafka-python-2.0.1-181ca166-c98c-426a-91f3-deeb9e9574de for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:06:12,617] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 32 (__consumer_offsets-12) (reason: Adding new member kafka-python-2.0.1-181ca166-c98c-426a-91f3-deeb9e9574de with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:06:17,632] INFO [GroupCoordinator 0]: Member kafka-python-2.0.1-c2e0c9a9-34cf-4961-8282-81a07688eee9 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:06:17,633] INFO [GroupCoordinator 0]: Stabilized group my-group generation 33 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:06:17,635] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 33 (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:07:00,674] INFO [GroupCoordinator 0]: Member kafka-python-2.0.1-181ca166-c98c-426a-91f3-deeb9e9574de in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:07:00,675] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 33 (__consumer_offsets-12) (reason: removing member kafka-python-2.0.1-181ca166-c98c-426a-91f3-deeb9e9574de on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:07:00,675] INFO [GroupCoordinator 0]: Group my-group with generation 34 is now empty (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:07:06,153] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group my-group in Empty state. Created a new member id kafka-python-2.0.1-71f92a6c-96c2-4919-b3c3-bf42f8b72f67 for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:07:06,154] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 34 (__consumer_offsets-12) (reason: Adding new member kafka-python-2.0.1-71f92a6c-96c2-4919-b3c3-bf42f8b72f67 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:07:06,154] INFO [GroupCoordinator 0]: Stabilized group my-group generation 35 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:07:06,156] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 35 (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:07:55,394] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group my-group in Stable state. Created a new member id kafka-python-2.0.1-20237158-3050-43f1-91a8-cd4dcdd29afe for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:07:55,394] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 35 (__consumer_offsets-12) (reason: Adding new member kafka-python-2.0.1-20237158-3050-43f1-91a8-cd4dcdd29afe with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:07:56,189] INFO [GroupCoordinator 0]: Member kafka-python-2.0.1-71f92a6c-96c2-4919-b3c3-bf42f8b72f67 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:07:56,190] INFO [GroupCoordinator 0]: Stabilized group my-group generation 36 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:07:56,192] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 36 (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:08:57,616] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2020-04-22 06:11:46,248] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group my-group in Stable state. Created a new member id kafka-python-2.0.1-b23e5c75-ab8d-4fbc-abbd-26e7f476fc98 for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:11:46,248] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 36 (__consumer_offsets-12) (reason: Adding new member kafka-python-2.0.1-b23e5c75-ab8d-4fbc-abbd-26e7f476fc98 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:11:48,464] INFO [GroupCoordinator 0]: Member kafka-python-2.0.1-20237158-3050-43f1-91a8-cd4dcdd29afe in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:11:48,465] INFO [GroupCoordinator 0]: Stabilized group my-group generation 37 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:11:48,467] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 37 (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:13:08,898] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group my-group in Stable state. Created a new member id kafka-python-2.0.1-0d4c68f7-285c-4c96-b649-210f4195b384 for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:13:08,898] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 37 (__consumer_offsets-12) (reason: Adding new member kafka-python-2.0.1-0d4c68f7-285c-4c96-b649-210f4195b384 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:13:13,560] INFO [GroupCoordinator 0]: Member kafka-python-2.0.1-b23e5c75-ab8d-4fbc-abbd-26e7f476fc98 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:13:13,561] INFO [GroupCoordinator 0]: Stabilized group my-group generation 38 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:13:13,563] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 38 (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:14:59,652] INFO [GroupCoordinator 0]: Member kafka-python-2.0.1-0d4c68f7-285c-4c96-b649-210f4195b384 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:14:59,652] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 38 (__consumer_offsets-12) (reason: removing member kafka-python-2.0.1-0d4c68f7-285c-4c96-b649-210f4195b384 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:14:59,652] INFO [GroupCoordinator 0]: Group my-group with generation 39 is now empty (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:18:57,627] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2020-04-22 06:28:57,635] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2020-04-22 06:37:37,239] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group my-group in Empty state. Created a new member id kafka-python-2.0.1-548d7dac-83b2-4cd7-8562-3aed879da7c1 for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:37:37,240] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 39 (__consumer_offsets-12) (reason: Adding new member kafka-python-2.0.1-548d7dac-83b2-4cd7-8562-3aed879da7c1 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:37:37,241] INFO [GroupCoordinator 0]: Stabilized group my-group generation 40 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:37:37,242] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 40 (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:38:57,645] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2020-04-22 06:41:19,483] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group my-group in Stable state. Created a new member id kafka-python-2.0.1-80a2a716-5674-426b-813b-2c11d78ed9d9 for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:41:19,483] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 40 (__consumer_offsets-12) (reason: Adding new member kafka-python-2.0.1-80a2a716-5674-426b-813b-2c11d78ed9d9 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:41:23,501] INFO [GroupCoordinator 0]: Member kafka-python-2.0.1-548d7dac-83b2-4cd7-8562-3aed879da7c1 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:41:23,502] INFO [GroupCoordinator 0]: Stabilized group my-group generation 41 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:41:23,503] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 41 (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:41:33,507] INFO [GroupCoordinator 0]: Member kafka-python-2.0.1-80a2a716-5674-426b-813b-2c11d78ed9d9 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:41:33,507] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 41 (__consumer_offsets-12) (reason: removing member kafka-python-2.0.1-80a2a716-5674-426b-813b-2c11d78ed9d9 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:41:33,507] INFO [GroupCoordinator 0]: Group my-group with generation 42 is now empty (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:41:39,493] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group my-group in Empty state. Created a new member id kafka-python-2.0.1-e02381a3-6092-4b90-ba67-eb1c75460d59 for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:41:39,494] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 42 (__consumer_offsets-12) (reason: Adding new member kafka-python-2.0.1-e02381a3-6092-4b90-ba67-eb1c75460d59 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:41:39,495] INFO [GroupCoordinator 0]: Stabilized group my-group generation 43 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:41:39,496] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 43 (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:42:46,835] INFO [GroupCoordinator 0]: Member kafka-python-2.0.1-e02381a3-6092-4b90-ba67-eb1c75460d59 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:42:46,835] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 43 (__consumer_offsets-12) (reason: removing member kafka-python-2.0.1-e02381a3-6092-4b90-ba67-eb1c75460d59 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:42:46,836] INFO [GroupCoordinator 0]: Group my-group with generation 44 is now empty (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:43:02,982] INFO [GroupCoordinator 0]: Dynamic Member with unknown member id joins group my-group in Empty state. Created a new member id kafka-python-2.0.1-d67fdbe8-cdf4-41c6-96e7-d956f449d0f1 for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:43:02,983] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 44 (__consumer_offsets-12) (reason: Adding new member kafka-python-2.0.1-d67fdbe8-cdf4-41c6-96e7-d956f449d0f1 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:43:02,984] INFO [GroupCoordinator 0]: Stabilized group my-group generation 45 (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:43:02,985] INFO [GroupCoordinator 0]: Assignment received from leader for group my-group for generation 45 (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:46:18,370] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2020-04-22 06:46:18,371] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2020-04-22 06:46:18,372] INFO [KafkaServer id=0] Starting controlled shutdown (kafka.server.KafkaServer)
[2020-04-22 06:46:18,436] WARN Session 0x100066854230000 for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:382)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:75)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:363)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1223)
[2020-04-22 06:46:18,542] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2020-04-22 06:46:18,542] INFO [ZooKeeperClient Kafka server] Connected. (kafka.zookeeper.ZooKeeperClient)
[2020-04-22 06:46:19,638] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:19,639] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:19,740] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2020-04-22 06:46:21,287] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:21,288] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:23,319] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:23,320] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:25,409] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:25,409] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:27,381] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:27,382] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:28,384] INFO [GroupCoordinator 0]: Member kafka-python-2.0.1-d67fdbe8-cdf4-41c6-96e7-d956f449d0f1 in group my-group has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:46:28,384] INFO [GroupCoordinator 0]: Preparing to rebalance group my-group in state PreparingRebalance with old generation 45 (__consumer_offsets-12) (reason: removing member kafka-python-2.0.1-d67fdbe8-cdf4-41c6-96e7-d956f449d0f1 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:46:28,384] INFO [GroupCoordinator 0]: Group my-group with generation 46 is now empty (__consumer_offsets-12) (kafka.coordinator.group.GroupCoordinator)
[2020-04-22 06:46:28,825] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:28,826] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:30,232] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:30,233] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:32,199] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:32,200] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:33,482] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:33,483] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:35,323] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:35,323] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:36,485] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:36,485] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:37,627] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:37,627] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:39,132] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:39,133] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:40,246] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:40,247] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:42,284] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:42,285] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:43,839] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:43,839] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:45,465] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:45,466] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:47,423] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:47,424] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:49,216] INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2020-04-22 06:46:49,217] INFO Socket error occurred: localhost/0:0:0:0:0:0:0:1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
